# GET http://localhost:3000

# GET http://localhost:3000/api/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDcyNTgxLCJleHAiOjE2MjA1NTg5ODF9.RxwOSckIXssjhJySKTuAVQuz7O-DP3Ty7lhxvRHT5rA 

# GET http://localhost:3000/api/users/1

 GET http://localhost:3000/api/posts

# GET http://localhost:3000/api/posts/1

# DELETE http://localhost:3000/api/deleterecord/1

# DELETE http://localhost:3000/api/deleterecord/1/3


# POST http://localhost:3000/api/auth/login
# content-type: "application/json"

# {
#   "email": "test@test.pl",
#   "password": "test"
# }

# POST http://localhost:3000/api/auth/refresh
# Content-Type: application/json

# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDczNDU0LCJleHAiOjE2MjA5OTkwNTR9.-ln17Eb25H4O7x8dXKzXmNEaKn6z-n9WSqvSQR-eyCY"
# }

# POST http://localhost:3000/api/add/record
# content-type: "application/json"

# {
#   "title": "pierwszy dodany tytuł",
#   "lead": "nie wiem jak mam rozumieć lead",
#   "content": "pierwza dodana zawartość"
# }